name: Continuous Integration

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

env:
  CC: /usr/bin/gcc-10
  CXX: /usr/bin/g++-10

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        install: [YES, NO]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: friendlyanon/fetch-core-count@v1
        id: cores

      - name: install GCC 10
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-10 g++-10

      - name: Install
        if: matrix.install == 'YES'
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE:STRING=Debug
          cmake --build build --config Debug
          sudo cmake --install build --config Debug
          rm -rf build

      - name: Configure
        run: cmake -S test -B build
          -DCMAKE_BUILD_TYPE:STRING=Debug
          -DTEST_INSTALLED_VERSION:BOOL=${{ matrix.install }}

      - name: Build
        run: cmake --build build --config Debug
          -j ${{ steps.cores.outputs.plus_one }}

      - name: Test
        working-directory: build
        run: ctest -C Debug -VV -j ${{ steps.cores.outputs.plus_one }}
